name: Limit PRs

on:
  pull_request:
    branches:
      - main

jobs:
  limit_main_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: LukBukkit/action-pr-limits@v1
        with:
          allowlist: |
            development
